build: add org.apache.http.legacy to maps-app
Required for instrumentation tests running on Android 9+ to avoid NoClassDefFoundError: org/apache/http/ProtocolVersion.